In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data)

print(df[['Name', 'Qualification', 'Age']])

     Name Qualification  Age
0     Jai           Msc   27
1  Princi            MA   24
2  Gaurav           MCA   22
3    Anuj           Phd   32

In [ ]:
df.to_csv('out.csv')

In [ ]:
ff = pd.read_csv('/content/out.csv', index_col=0)
ff

     Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd

In [ ]:
#converting raw data into csv
import csv

raw_data = [
    ["John Doe", 25],
    ["Jane Smith", 30],
    ["Mike Johnson", 35],
    ["Sarah Williams", 28]
]

with open('output.csv', 'w') as f:
  f_write = csv.writer(f)

  f_write.writerow(['Name', 'Age'])

  for row in raw_data:
    f_write.writerow(row)

In [ ]:
df = pd.read_csv('output.csv')
df

             Name  Age
0        John Doe   25
1      Jane Smith   30
2    Mike Johnson   35
3  Sarah Williams   28

In [ ]:
import json

with open('/content/output.csv', 'r') as f:
  f_read = csv.DictReader(f)
  data  = list(f_read)

with open('en.json', 'w') as j:
  json.dump(data, j, indent=4)  #csv to json

In [ ]:
with open('/content/en.json', 'r') as j:
  json_data = json.load(j)
  headers = list(json_data[0].keys())

with open('ouutput1.csv', 'w') as f:
  f_write1 = csv.DictWriter(f, fieldnames=headers)
  f_write1.writeheader()
  f_write1.writerows(json_data)  #json to csv

In [ ]:
jj = pd.read_json('/content/en.json')

jj